import { ReactNode } from "react"

import {
  AngularIcon,
  AstroIcon,
  DjangoIcon,
  ExpressIcon,
  FigmaIcon2,
  FirebaseIcon,
  GitIcon,
  JavaIcon,
  MongoIcon,
  MySqlIcon,
  NeonDBIcon,
  NextjsIcon,
  PostgresIcon,
  PrismaIcon,
  PythonIcon,
  QueryIcon,
  ReactIcon,
  ReduxIcon,
  StrapiIcon,
  TailwindIcon,
  TypeScriptIcon,
  VitestIcon,
  ZodIcon,
} from "./SkillsIcons"

export const ICONS: Record<string, ReactNode> = {
  "Next.js": <NextjsIcon/>,
  "zod-test": <NextjsIcon/>,
  "React Query": <QueryIcon />,
  "Express.js": <ExpressIcon />,
  React: <ReactIcon />,
  Angular: <AngularIcon />,
  Tailwind: <TailwindIcon />,
  TypeScript: <TypeScriptIcon />,
  MongoDB: <MongoIcon />,
  MySQL: <MySqlIcon />,
  Git: <GitIcon />,
  Figma: <FigmaIcon2 />,
  Django: <DjangoIcon />,
  Python: <PythonIcon />,
  Firebase: <FirebaseIcon />,
  Java: <JavaIcon />,
  Redux: <ReduxIcon />,
  Prisma: <PrismaIcon />,
  Vitest: <VitestIcon />,
  PostgreSQL: <PostgresIcon />,
  Astro: <AstroIcon />,
  NeonDB: <NeonDBIcon />,
  Zod: <ZodIcon />,
  Strapi: <StrapiIcon />,
}
